/**
 * Stable infrastructure failure / diagnostic codes for mission runtime.
 * Presentation may map these to user-facing strings; codes are authoritative.
 */

export const MISSION_INFRASTRUCTURE_CODES = [
  'MISSION_LAUNCH_INTENT_INVALID',
  'MISSION_DEFINITION_UNAVAILABLE',
  'MISSION_DEFINITION_NOT_FOUND',
  'MISSION_CONTENT_INVALID',
  'MISSION_AIRCRAFT_INCOMPATIBLE',
  /** Retained for compatibility with pre-capture builds. */
  'MISSION_CAPTURE_NOT_ENABLED',
  'PHOTO_CAPTURE_ALREADY_PENDING',
  'PHOTO_CAPTURE_NOT_ACTIVE',
  'PHOTO_CAPTURE_WRONG_CAMERA_MODE',
  'PHOTO_CAPTURE_SESSION_STALE',
  'PHOTO_CAPTURE_OBJECTIVE_STALE',
  'PHOTO_CAPTURE_SPATIAL_UNAVAILABLE',
  'PHOTO_CAPTURE_EVIDENCE_INVALID',
  'PHOTO_CAPTURE_SCORING_FAILED',
  'PHOTO_PRESENTATION_CAPTURE_FAILED',
  'PHOTO_OBJECTIVE_ALREADY_COMPLETED',
  'MISSION_RETRY_RUNTIME_UNAVAILABLE',
  'MISSION_RESULT_AGGREGATION_FAILED',
  'LOCATION_DEFINITION_UNAVAILABLE',
  'LOCATION_PACKAGE_NOT_FOUND',
  'LOCATION_PACKAGE_VERSION_UNSUPPORTED',
  'LOCATION_CONTENT_INVALID',
  'LOCATION_VALIDATION_FAILED',
  'LOCATION_VISUAL_BUILD_FAILED',
  'LOCATION_COLLISION_BUILD_FAILED',
  'LOCATION_QUERY_INSTALL_FAILED',
  'LOCATION_PREVIOUS_COLLISION_RESTORE_FAILED',
  'LOCATION_LOAD_CANCELLED',
  'STALE_LOCATION_GENERATION',
  'LOCATION_UNLOAD_FAILED',
  'LOCATION_RUNTIME_LOAD_FAILED',
  'AIRCRAFT_INCOMPATIBLE',
  'AIRCRAFT_CAPABILITY_ADAPTER_FAILED',
  'CAMERA_RIG_RESOLUTION_FAILED',
  'SPATIAL_QUERY_UNAVAILABLE',
  'AUTHORITATIVE_STEP_OBSERVER_FAILED',
  'STALE_RUNTIME_SESSION',
] as const;

export type MissionInfrastructureCode = (typeof MISSION_INFRASTRUCTURE_CODES)[number];

export interface MissionRuntimeDiagnostic {
  readonly code: MissionInfrastructureCode;
  readonly message: string;
  readonly details?: Readonly<Record<string, unknown>>;
}
