import type { WeatherPresetDefinition } from '../models/weather.models';
import { ZERO_WIND_STATE } from '../models/wind.models';

function dir(x: number, z: number): { x: number; y: number; z: number } {
  const len = Math.hypot(x, z) || 1;
  return { x: x / len, y: 0, z: z / len };
}

const calmWind = { ...ZERO_WIND_STATE };

/** Universal + environment-specific weather presets (config-driven). */
export const WEATHER_PRESETS: WeatherPresetDefinition[] = [
  // —— Universal ——
  {
    id: 'calm',
    name: 'Calm',
    description: 'No wind, clear visibility. Standard race records.',
    environments: '*',
    state: {
      wind: { ...calmWind },
      visibility: 1,
      fogDensity: 0.3,
      cloudCoverage: 0.1,
      precipitationType: 'none',
      precipitationIntensity: 0,
      surfaceWetness: 0,
      ambientLightMultiplier: 1,
      sunLightMultiplier: 1,
      temperatureVisualHint: 0.55,
      transitionDurationSeconds: 4,
      recordCategory: 'standard',
      difficultyClass: 'standard',
    },
  },
  {
    id: 'light-breeze',
    name: 'Light Breeze',
    description: 'Low steady wind with very mild gusts.',
    environments: '*',
    state: {
      wind: {
        enabled: true,
        baseDirection: dir(1, 0.2),
        baseSpeed: 2,
        gustStrength: 0.6,
        gustFrequency: 0.08,
        turbulence: 0.12,
        verticalDraftStrength: 0,
        seed: 41001,
      },
      visibility: 1,
      fogDensity: 0.32,
      cloudCoverage: 0.2,
      precipitationType: 'none',
      precipitationIntensity: 0,
      surfaceWetness: 0,
      ambientLightMultiplier: 1,
      sunLightMultiplier: 1,
      temperatureVisualHint: 0.5,
      transitionDurationSeconds: 5,
      recordCategory: 'standard',
      difficultyClass: 'standard',
    },
  },
  {
    id: 'crosswind',
    name: 'Crosswind',
    description: 'Medium lateral wind with moderate gusts.',
    environments: '*',
    state: {
      wind: {
        enabled: true,
        baseDirection: dir(1, 0),
        baseSpeed: 4.5,
        gustStrength: 1.8,
        gustFrequency: 0.12,
        turbulence: 0.28,
        verticalDraftStrength: 0.15,
        seed: 41002,
      },
      visibility: 0.95,
      fogDensity: 0.38,
      cloudCoverage: 0.35,
      precipitationType: 'none',
      precipitationIntensity: 0,
      surfaceWetness: 0,
      ambientLightMultiplier: 0.98,
      sunLightMultiplier: 0.95,
      temperatureVisualHint: 0.48,
      transitionDurationSeconds: 5,
      recordCategory: 'challenge',
      difficultyClass: 'challenge',
    },
  },
  {
    id: 'gusty',
    name: 'Gusty',
    description: 'Stronger variable wind with noticeable turbulence.',
    environments: '*',
    state: {
      wind: {
        enabled: true,
        baseDirection: dir(0.7, 0.7),
        baseSpeed: 6.5,
        gustStrength: 2.8,
        gustFrequency: 0.18,
        turbulence: 0.45,
        verticalDraftStrength: 0.35,
        seed: 41003,
      },
      visibility: 0.9,
      fogDensity: 0.42,
      cloudCoverage: 0.45,
      precipitationType: 'none',
      precipitationIntensity: 0,
      surfaceWetness: 0,
      ambientLightMultiplier: 0.95,
      sunLightMultiplier: 0.92,
      temperatureVisualHint: 0.45,
      transitionDurationSeconds: 6,
      recordCategory: 'challenge',
      difficultyClass: 'challenge',
    },
  },

  // —— Alpine ——
  {
    id: 'alpine-valley-morning',
    name: 'Valley Morning',
    description: 'Cool alpine morning with soft haze.',
    environments: ['alpine-training-valley'],
    state: {
      wind: {
        enabled: true,
        baseDirection: dir(0.4, 1),
        baseSpeed: 1.5,
        gustStrength: 0.4,
        gustFrequency: 0.06,
        turbulence: 0.1,
        verticalDraftStrength: 0.05,
        seed: 42001,
      },
      visibility: 0.92,
      fogDensity: 0.55,
      cloudCoverage: 0.25,
      precipitationType: 'none',
      precipitationIntensity: 0,
      surfaceWetness: 0.05,
      ambientLightMultiplier: 0.95,
      sunLightMultiplier: 0.9,
      temperatureVisualHint: 0.35,
      transitionDurationSeconds: 6,
      recordCategory: 'standard',
      difficultyClass: 'standard',
    },
  },
  {
    id: 'alpine-mountain-breeze',
    name: 'Mountain Breeze',
    description: 'Steady valley wind along the corridor.',
    environments: ['alpine-training-valley'],
    state: {
      wind: {
        enabled: true,
        baseDirection: dir(0.2, 1),
        baseSpeed: 3.2,
        gustStrength: 1.0,
        gustFrequency: 0.1,
        turbulence: 0.2,
        verticalDraftStrength: 0.1,
        seed: 42002,
      },
      visibility: 0.95,
      fogDensity: 0.4,
      cloudCoverage: 0.3,
      precipitationType: 'none',
      precipitationIntensity: 0,
      surfaceWetness: 0,
      ambientLightMultiplier: 1,
      sunLightMultiplier: 0.98,
      temperatureVisualHint: 0.4,
      transitionDurationSeconds: 5,
      recordCategory: 'standard',
      difficultyClass: 'standard',
    },
  },
  {
    id: 'alpine-light-fog',
    name: 'Light Fog',
    description: 'Reduced visibility with calm air.',
    environments: ['alpine-training-valley'],
    state: {
      wind: { ...calmWind },
      visibility: 0.55,
      fogDensity: 0.78,
      cloudCoverage: 0.7,
      precipitationType: 'none',
      precipitationIntensity: 0,
      surfaceWetness: 0.1,
      ambientLightMultiplier: 0.85,
      sunLightMultiplier: 0.7,
      temperatureVisualHint: 0.35,
      transitionDurationSeconds: 7,
      recordCategory: 'challenge',
      difficultyClass: 'challenge',
    },
  },
  {
    id: 'alpine-light-snow',
    name: 'Light Snow',
    description: 'Gentle snowfall with light breeze.',
    environments: ['alpine-training-valley'],
    state: {
      wind: {
        enabled: true,
        baseDirection: dir(-0.5, 0.8),
        baseSpeed: 2.2,
        gustStrength: 0.7,
        gustFrequency: 0.09,
        turbulence: 0.15,
        verticalDraftStrength: 0.05,
        seed: 42004,
      },
      visibility: 0.7,
      fogDensity: 0.62,
      cloudCoverage: 0.75,
      precipitationType: 'lightSnow',
      precipitationIntensity: 0.55,
      surfaceWetness: 0.2,
      ambientLightMultiplier: 0.9,
      sunLightMultiplier: 0.75,
      temperatureVisualHint: 0.15,
      transitionDurationSeconds: 7,
      recordCategory: 'challenge',
      difficultyClass: 'challenge',
    },
  },

  // —— Desert ——
  {
    id: 'desert-calm',
    name: 'Desert Calm',
    description: 'Hot still air over the yard.',
    environments: ['desert-industrial-yard'],
    state: {
      wind: { ...calmWind },
      visibility: 1,
      fogDensity: 0.28,
      cloudCoverage: 0.05,
      precipitationType: 'none',
      precipitationIntensity: 0,
      surfaceWetness: 0,
      ambientLightMultiplier: 1.05,
      sunLightMultiplier: 1.1,
      temperatureVisualHint: 0.85,
      transitionDurationSeconds: 4,
      recordCategory: 'standard',
      difficultyClass: 'standard',
    },
  },
  {
    id: 'desert-dry-crosswind',
    name: 'Dry Crosswind',
    description: 'Steady crosswind across the compound.',
    environments: ['desert-industrial-yard'],
    state: {
      wind: {
        enabled: true,
        baseDirection: dir(1, 0.15),
        baseSpeed: 4.2,
        gustStrength: 1.5,
        gustFrequency: 0.11,
        turbulence: 0.25,
        verticalDraftStrength: 0.1,
        seed: 43002,
      },
      visibility: 0.92,
      fogDensity: 0.36,
      cloudCoverage: 0.15,
      precipitationType: 'none',
      precipitationIntensity: 0,
      surfaceWetness: 0,
      ambientLightMultiplier: 1,
      sunLightMultiplier: 1.05,
      temperatureVisualHint: 0.8,
      transitionDurationSeconds: 5,
      recordCategory: 'challenge',
      difficultyClass: 'challenge',
    },
  },
  {
    id: 'desert-gusty-yard',
    name: 'Gusty Yard',
    description: 'Strong gusts between containers and hangars.',
    environments: ['desert-industrial-yard'],
    state: {
      wind: {
        enabled: true,
        baseDirection: dir(0.85, 0.5),
        baseSpeed: 6.8,
        gustStrength: 3.0,
        gustFrequency: 0.2,
        turbulence: 0.5,
        verticalDraftStrength: 0.25,
        seed: 43003,
      },
      visibility: 0.85,
      fogDensity: 0.45,
      cloudCoverage: 0.25,
      precipitationType: 'dust',
      precipitationIntensity: 0.35,
      surfaceWetness: 0,
      ambientLightMultiplier: 0.95,
      sunLightMultiplier: 0.95,
      temperatureVisualHint: 0.82,
      transitionDurationSeconds: 6,
      recordCategory: 'challenge',
      difficultyClass: 'challenge',
    },
  },
  {
    id: 'desert-dust-haze',
    name: 'Dust Haze',
    description: 'Dusty air with reduced visibility and breeze.',
    environments: ['desert-industrial-yard'],
    state: {
      wind: {
        enabled: true,
        baseDirection: dir(1, -0.3),
        baseSpeed: 3.5,
        gustStrength: 1.2,
        gustFrequency: 0.14,
        turbulence: 0.3,
        verticalDraftStrength: 0.08,
        seed: 43004,
      },
      visibility: 0.6,
      fogDensity: 0.7,
      cloudCoverage: 0.4,
      precipitationType: 'dust',
      precipitationIntensity: 0.65,
      surfaceWetness: 0,
      ambientLightMultiplier: 0.88,
      sunLightMultiplier: 0.8,
      temperatureVisualHint: 0.78,
      transitionDurationSeconds: 7,
      recordCategory: 'challenge',
      difficultyClass: 'challenge',
    },
  },

  // —— Coastal ——
  {
    id: 'coastal-calm',
    name: 'Coastal Calm',
    description: 'Still morning air on the plateau.',
    environments: ['coastal-ruins'],
    state: {
      wind: { ...calmWind },
      visibility: 1,
      fogDensity: 0.32,
      cloudCoverage: 0.2,
      precipitationType: 'none',
      precipitationIntensity: 0,
      surfaceWetness: 0.05,
      ambientLightMultiplier: 1,
      sunLightMultiplier: 1,
      temperatureVisualHint: 0.55,
      transitionDurationSeconds: 4,
      recordCategory: 'standard',
      difficultyClass: 'standard',
    },
  },
  {
    id: 'coastal-sea-breeze',
    name: 'Sea Breeze',
    description: 'Onshore breeze from the water.',
    environments: ['coastal-ruins'],
    state: {
      wind: {
        enabled: true,
        baseDirection: dir(0.2, -1),
        baseSpeed: 3.8,
        gustStrength: 1.2,
        gustFrequency: 0.1,
        turbulence: 0.22,
        verticalDraftStrength: 0.12,
        seed: 44002,
      },
      visibility: 0.95,
      fogDensity: 0.4,
      cloudCoverage: 0.35,
      precipitationType: 'none',
      precipitationIntensity: 0,
      surfaceWetness: 0.1,
      ambientLightMultiplier: 1,
      sunLightMultiplier: 0.98,
      temperatureVisualHint: 0.52,
      transitionDurationSeconds: 5,
      recordCategory: 'standard',
      difficultyClass: 'standard',
    },
  },
  {
    id: 'coastal-cloudy',
    name: 'Cloudy Coast',
    description: 'Overcast skies with light wind.',
    environments: ['coastal-ruins'],
    state: {
      wind: {
        enabled: true,
        baseDirection: dir(-0.6, -0.8),
        baseSpeed: 2.5,
        gustStrength: 0.8,
        gustFrequency: 0.08,
        turbulence: 0.18,
        verticalDraftStrength: 0.05,
        seed: 44003,
      },
      visibility: 0.85,
      fogDensity: 0.5,
      cloudCoverage: 0.8,
      precipitationType: 'none',
      precipitationIntensity: 0,
      surfaceWetness: 0.15,
      ambientLightMultiplier: 0.85,
      sunLightMultiplier: 0.65,
      temperatureVisualHint: 0.45,
      transitionDurationSeconds: 6,
      recordCategory: 'standard',
      difficultyClass: 'standard',
    },
  },
  {
    id: 'coastal-light-rain',
    name: 'Light Rain',
    description: 'Sea breeze with light rain and moderate visibility.',
    environments: ['coastal-ruins'],
    state: {
      wind: {
        enabled: true,
        baseDirection: dir(0.3, -1),
        baseSpeed: 3.5,
        gustStrength: 1.4,
        gustFrequency: 0.12,
        turbulence: 0.25,
        verticalDraftStrength: 0.1,
        seed: 44004,
      },
      visibility: 0.7,
      fogDensity: 0.58,
      cloudCoverage: 0.85,
      precipitationType: 'rain',
      precipitationIntensity: 0.55,
      surfaceWetness: 0.7,
      ambientLightMultiplier: 0.8,
      sunLightMultiplier: 0.55,
      temperatureVisualHint: 0.42,
      transitionDurationSeconds: 6,
      recordCategory: 'challenge',
      difficultyClass: 'challenge',
    },
  },
  {
    id: 'coastal-sea-fog',
    name: 'Sea Fog',
    description: 'Thick coastal fog — gates remain readable.',
    environments: ['coastal-ruins'],
    state: {
      wind: {
        enabled: true,
        baseDirection: dir(0.1, -1),
        baseSpeed: 1.8,
        gustStrength: 0.5,
        gustFrequency: 0.07,
        turbulence: 0.12,
        verticalDraftStrength: 0.05,
        seed: 44005,
      },
      visibility: 0.45,
      fogDensity: 0.82,
      cloudCoverage: 0.9,
      precipitationType: 'none',
      precipitationIntensity: 0,
      surfaceWetness: 0.35,
      ambientLightMultiplier: 0.75,
      sunLightMultiplier: 0.5,
      temperatureVisualHint: 0.4,
      transitionDurationSeconds: 8,
      recordCategory: 'challenge',
      difficultyClass: 'challenge',
    },
  },
];

const PRESET_BY_ID = new Map(
  WEATHER_PRESETS.map((p) => [p.id, p] as const),
);

export function getWeatherPreset(
  id: string,
): WeatherPresetDefinition | undefined {
  return PRESET_BY_ID.get(id);
}

export function listWeatherPresetsForEnvironment(
  environmentId: string,
): WeatherPresetDefinition[] {
  return WEATHER_PRESETS.filter(
    (p) =>
      p.environments === '*' ||
      (Array.isArray(p.environments) &&
        p.environments.includes(environmentId)),
  );
}

export function isWeatherPresetSupported(
  presetId: string,
  environmentId: string,
): boolean {
  const preset = getWeatherPreset(presetId);
  if (!preset) {
    return false;
  }
  if (preset.environments === '*') {
    return true;
  }
  return preset.environments.includes(environmentId);
}
