import {
  asCatalogReleaseId,
  asComponentId,
  asComponentRevisionId,
  gramsToKg,
  kg,
  m,
  mmToM,
  mAhToAh,
  V,
  A,
  ohm,
  W,
  vec3,
  type ComponentRevisionId,
} from '@fpv/engineering-kernel';
import type {
  CatalogRelease,
  ComponentCatalogSnapshot,
  ComponentRevision,
  DisplayMetadata,
  EngineeringDataQuality,
} from './models';

const curated: EngineeringDataQuality = {
  provenance: 'curated',
  confidence: 'medium',
};

function display(
  name: string,
  manufacturer: string,
  tags: string[] = [],
): DisplayMetadata {
  return {
    displayName: name,
    description: name,
    manufacturerLabel: manufacturer,
    categoryLabels: tags,
    thumbnailKey: null,
    tags,
  };
}

function rev(
  componentId: string,
  revision: string,
  partial: Omit<
    ComponentRevision,
    'componentId' | 'revisionId' | 'schemaVersion' | 'source' | 'releaseStatus'
  >,
): ComponentRevision {
  return {
    componentId: asComponentId(componentId),
    revisionId: asComponentRevisionId(revision),
    source: 'official',
    releaseStatus: 'published',
    schemaVersion: '1.1.0',
    ...partial,
  };
}

/** Official v1.1 catalog — physics-relevant components for factory + future builder. */
export const OFFICIAL_COMPONENT_REVISIONS: readonly ComponentRevision[] = [
  // Frames
  rev('frame-cine-ducted-220', 'frame-cine-ducted-220@1', {
    componentType: 'frame',
    display: display('Cine Ducted 220', 'Skyward Dynamics', ['cinewhoop']),
    massKg: gramsToKg(95),
    dimensions: { widthMeters: m(0.28), lengthMeters: m(0.3), heightMeters: m(0.05) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['16x16', '20x20'],
    compatibilityTags: ['ducted', 'protected'],
    dataQuality: curated,
    engineering: {
      type: 'frame',
      frame: {
        wheelbaseMeters: m(0.22),
        armPositions: [
          vec3(0.078, 0.078, 0),
          vec3(-0.078, 0.078, 0),
          vec3(-0.078, -0.078, 0),
          vec3(0.078, -0.078, 0),
        ],
        motorMountPattern: '16x16',
        supportedPropDiameterMinM: m(0.1),
        supportedPropDiameterMaxM: m(0.14),
        batteryMountZone: {
          widthMeters: m(0.04),
          lengthMeters: m(0.1),
          heightMeters: m(0.03),
        },
        maxRecommendedTakeoffMassKg: kg(0.55),
        dragProfileFactor: 1.15,
        frameInertiaFactor: 1.0,
      },
    },
  }),
  rev('frame-hybrid-speed-280', 'frame-hybrid-speed-280@1', {
    componentType: 'frame',
    display: display('Hybrid Speed 280', 'Vector Forge', ['hybrid']),
    massKg: gramsToKg(180),
    dimensions: { widthMeters: m(0.32), lengthMeters: m(0.34), heightMeters: m(0.06) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['19x19'],
    compatibilityTags: ['open'],
    dataQuality: curated,
    engineering: {
      type: 'frame',
      frame: {
        wheelbaseMeters: m(0.28),
        armPositions: [
          vec3(0.099, 0.099, 0),
          vec3(-0.099, 0.099, 0),
          vec3(-0.099, -0.099, 0),
          vec3(0.099, -0.099, 0),
        ],
        motorMountPattern: '19x19',
        supportedPropDiameterMinM: m(0.12),
        supportedPropDiameterMaxM: m(0.16),
        batteryMountZone: {
          widthMeters: m(0.05),
          lengthMeters: m(0.14),
          heightMeters: m(0.04),
        },
        maxRecommendedTakeoffMassKg: kg(1.1),
        dragProfileFactor: 0.55,
        frameInertiaFactor: 1.35,
      },
    },
  }),
  rev('frame-nano-85', 'frame-nano-85@1', {
    componentType: 'frame',
    display: display('Nano 85', 'MicroNest Labs', ['micro']),
    massKg: gramsToKg(22),
    dimensions: { widthMeters: m(0.1), lengthMeters: m(0.1), heightMeters: m(0.03) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['9x9'],
    compatibilityTags: ['whoop'],
    dataQuality: curated,
    engineering: {
      type: 'frame',
      frame: {
        wheelbaseMeters: m(0.085),
        armPositions: [
          vec3(0.03, 0.03, 0),
          vec3(-0.03, 0.03, 0),
          vec3(-0.03, -0.03, 0),
          vec3(0.03, -0.03, 0),
        ],
        motorMountPattern: '9x9',
        supportedPropDiameterMinM: m(0.04),
        supportedPropDiameterMaxM: m(0.07),
        batteryMountZone: {
          widthMeters: m(0.02),
          lengthMeters: m(0.04),
          heightMeters: m(0.015),
        },
        maxRecommendedTakeoffMassKg: kg(0.2),
        dragProfileFactor: 1.4,
        frameInertiaFactor: 0.35,
      },
    },
  }),
  rev('frame-racing-5in', 'frame-racing-5in@1', {
    componentType: 'frame',
    display: display('Racing 5in', 'Apex Racing Systems', ['racing']),
    massKg: gramsToKg(110),
    dimensions: { widthMeters: m(0.24), lengthMeters: m(0.24), heightMeters: m(0.04) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['16x16'],
    compatibilityTags: ['racing', '5inch'],
    dataQuality: curated,
    engineering: {
      type: 'frame',
      frame: {
        wheelbaseMeters: m(0.225),
        armPositions: [
          vec3(0.08, 0.08, 0),
          vec3(-0.08, 0.08, 0),
          vec3(-0.08, -0.08, 0),
          vec3(0.08, -0.08, 0),
        ],
        motorMountPattern: '16x16',
        supportedPropDiameterMinM: m(0.12),
        supportedPropDiameterMaxM: m(0.132),
        batteryMountZone: {
          widthMeters: m(0.04),
          lengthMeters: m(0.12),
          heightMeters: m(0.03),
        },
        maxRecommendedTakeoffMassKg: kg(0.75),
        dragProfileFactor: 0.7,
        frameInertiaFactor: 0.85,
      },
    },
  }),
  rev('frame-freestyle-5in', 'frame-freestyle-5in@1', {
    componentType: 'frame',
    display: display('Freestyle 5in', 'FluxCraft', ['freestyle']),
    massKg: gramsToKg(125),
    dimensions: { widthMeters: m(0.25), lengthMeters: m(0.25), heightMeters: m(0.045) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['16x16'],
    compatibilityTags: ['freestyle', '5inch'],
    dataQuality: curated,
    engineering: {
      type: 'frame',
      frame: {
        wheelbaseMeters: m(0.23),
        armPositions: [
          vec3(0.081, 0.081, 0),
          vec3(-0.081, 0.081, 0),
          vec3(-0.081, -0.081, 0),
          vec3(0.081, -0.081, 0),
        ],
        motorMountPattern: '16x16',
        supportedPropDiameterMinM: m(0.12),
        supportedPropDiameterMaxM: m(0.132),
        batteryMountZone: {
          widthMeters: m(0.045),
          lengthMeters: m(0.13),
          heightMeters: m(0.035),
        },
        maxRecommendedTakeoffMassKg: kg(0.85),
        dragProfileFactor: 0.75,
        frameInertiaFactor: 0.95,
      },
    },
  }),
  rev('frame-longrange-7in', 'frame-longrange-7in@1', {
    componentType: 'frame',
    display: display('Long Range 7in', 'Horizon Aero', ['long-range']),
    massKg: gramsToKg(160),
    dimensions: { widthMeters: m(0.32), lengthMeters: m(0.32), heightMeters: m(0.05) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['19x19'],
    compatibilityTags: ['7inch', 'long-range'],
    dataQuality: curated,
    engineering: {
      type: 'frame',
      frame: {
        wheelbaseMeters: m(0.3),
        armPositions: [
          vec3(0.106, 0.106, 0),
          vec3(-0.106, 0.106, 0),
          vec3(-0.106, -0.106, 0),
          vec3(0.106, -0.106, 0),
        ],
        motorMountPattern: '19x19',
        supportedPropDiameterMinM: m(0.16),
        supportedPropDiameterMaxM: m(0.18),
        batteryMountZone: {
          widthMeters: m(0.05),
          lengthMeters: m(0.16),
          heightMeters: m(0.04),
        },
        maxRecommendedTakeoffMassKg: kg(1.2),
        dragProfileFactor: 0.65,
        frameInertiaFactor: 1.5,
      },
    },
  }),

  // Motors
  rev('motor-1404-4500kv', 'motor-1404-4500kv@1', {
    componentType: 'motor',
    display: display('1404 4500KV', 'Skyward Dynamics'),
    massKg: gramsToKg(12),
    dimensions: { widthMeters: mmToM(18), lengthMeters: mmToM(18), heightMeters: mmToM(18) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['16x16'],
    compatibilityTags: ['4s'],
    dataQuality: curated,
    engineering: {
      type: 'motor',
      motor: {
        statorWidthMm: 14,
        statorHeightMm: 4,
        kv: 4500,
        voltageMin: V(11),
        voltageMax: V(17),
        maxContinuousCurrentA: A(18),
        maxContinuousPowerW: W(250),
        internalResistanceOhm: ohm(0.08),
        propellerDiameterMinM: m(0.1),
        propellerDiameterMaxM: m(0.14),
        responseTimeConstantS: 0.1,
        peakThrustHintNewtons: 2.3,
      },
    },
  }),
  rev('motor-2207-2450kv', 'motor-2207-2450kv@1', {
    componentType: 'motor',
    display: display('2207 2450KV', 'Vector Forge'),
    massKg: gramsToKg(33),
    dimensions: { widthMeters: mmToM(28), lengthMeters: mmToM(28), heightMeters: mmToM(22) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['19x19', '16x16'],
    compatibilityTags: ['6s'],
    dataQuality: curated,
    engineering: {
      type: 'motor',
      motor: {
        statorWidthMm: 22,
        statorHeightMm: 7,
        kv: 2450,
        voltageMin: V(14),
        voltageMax: V(26),
        maxContinuousCurrentA: A(40),
        maxContinuousPowerW: W(800),
        internalResistanceOhm: ohm(0.045),
        propellerDiameterMinM: m(0.12),
        propellerDiameterMaxM: m(0.16),
        responseTimeConstantS: 0.12,
        peakThrustHintNewtons: 5.5,
      },
    },
  }),
  rev('motor-1103-10000kv', 'motor-1103-10000kv@1', {
    componentType: 'motor',
    display: display('1103 10000KV', 'MicroNest Labs'),
    massKg: gramsToKg(3.5),
    dimensions: { widthMeters: mmToM(14), lengthMeters: mmToM(14), heightMeters: mmToM(12) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['9x9'],
    compatibilityTags: ['1s', '2s'],
    dataQuality: curated,
    engineering: {
      type: 'motor',
      motor: {
        statorWidthMm: 11,
        statorHeightMm: 3,
        kv: 10000,
        voltageMin: V(3.5),
        voltageMax: V(8.5),
        maxContinuousCurrentA: A(8),
        maxContinuousPowerW: W(40),
        internalResistanceOhm: ohm(0.15),
        propellerDiameterMinM: m(0.04),
        propellerDiameterMaxM: m(0.07),
        responseTimeConstantS: 0.04,
        peakThrustHintNewtons: 0.8,
      },
    },
  }),
  rev('motor-2306-2750kv', 'motor-2306-2750kv@1', {
    componentType: 'motor',
    display: display('2306 2750KV', 'Apex Racing Systems'),
    massKg: gramsToKg(32),
    dimensions: { widthMeters: mmToM(28), lengthMeters: mmToM(28), heightMeters: mmToM(20) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['16x16'],
    compatibilityTags: ['6s', 'racing'],
    dataQuality: curated,
    engineering: {
      type: 'motor',
      motor: {
        statorWidthMm: 23,
        statorHeightMm: 6,
        kv: 2750,
        voltageMin: V(14),
        voltageMax: V(26),
        maxContinuousCurrentA: A(45),
        maxContinuousPowerW: W(900),
        internalResistanceOhm: ohm(0.04),
        propellerDiameterMinM: m(0.12),
        propellerDiameterMaxM: m(0.132),
        responseTimeConstantS: 0.06,
        peakThrustHintNewtons: 6.2,
      },
    },
  }),
  rev('motor-2207-1950kv', 'motor-2207-1950kv@1', {
    componentType: 'motor',
    display: display('2207 1950KV', 'FluxCraft'),
    massKg: gramsToKg(34),
    dimensions: { widthMeters: mmToM(28), lengthMeters: mmToM(28), heightMeters: mmToM(22) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['16x16'],
    compatibilityTags: ['6s', 'freestyle'],
    dataQuality: curated,
    engineering: {
      type: 'motor',
      motor: {
        statorWidthMm: 22,
        statorHeightMm: 7,
        kv: 1950,
        voltageMin: V(14),
        voltageMax: V(26),
        maxContinuousCurrentA: A(38),
        maxContinuousPowerW: W(750),
        internalResistanceOhm: ohm(0.05),
        propellerDiameterMinM: m(0.12),
        propellerDiameterMaxM: m(0.132),
        responseTimeConstantS: 0.08,
        peakThrustHintNewtons: 5.0,
      },
    },
  }),
  rev('motor-2807-1500kv', 'motor-2807-1500kv@1', {
    componentType: 'motor',
    display: display('2807 1500KV', 'Horizon Aero'),
    massKg: gramsToKg(48),
    dimensions: { widthMeters: mmToM(34), lengthMeters: mmToM(34), heightMeters: mmToM(24) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['19x19'],
    compatibilityTags: ['6s', '7inch'],
    dataQuality: curated,
    engineering: {
      type: 'motor',
      motor: {
        statorWidthMm: 28,
        statorHeightMm: 7,
        kv: 1500,
        voltageMin: V(14),
        voltageMax: V(26),
        maxContinuousCurrentA: A(35),
        maxContinuousPowerW: W(700),
        internalResistanceOhm: ohm(0.055),
        propellerDiameterMinM: m(0.16),
        propellerDiameterMaxM: m(0.18),
        responseTimeConstantS: 0.14,
        peakThrustHintNewtons: 5.8,
      },
    },
  }),

  // Propellers
  rev('prop-ducted-3blade-120', 'prop-ducted-3blade-120@1', {
    componentType: 'propeller',
    display: display('Ducted 120mm 3-blade', 'Skyward Dynamics'),
    massKg: gramsToKg(3.5),
    dimensions: { widthMeters: m(0.12), lengthMeters: m(0.12), heightMeters: m(0.01) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['5mm'],
    compatibilityTags: ['ducted'],
    dataQuality: curated,
    engineering: {
      type: 'propeller',
      propeller: {
        diameterMeters: m(0.12),
        pitchMeters: m(0.045),
        bladeCount: 3,
        rotationalInertiaFactor: 0.8,
        recommendedRpmMin: 8000,
        recommendedRpmMax: 28000,
        thrustCoefficient: 0.095,
        powerCoefficient: 0.04,
        rotationDirections: ['either'],
      },
    },
  }),
  rev('prop-5x4x3', 'prop-5x4x3@1', {
    componentType: 'propeller',
    display: display('5x4x3', 'Apex Racing Systems'),
    massKg: gramsToKg(4.2),
    dimensions: { widthMeters: m(0.127), lengthMeters: m(0.127), heightMeters: m(0.012) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['5mm'],
    compatibilityTags: ['5inch'],
    dataQuality: curated,
    engineering: {
      type: 'propeller',
      propeller: {
        diameterMeters: m(0.127),
        pitchMeters: m(0.102),
        bladeCount: 3,
        rotationalInertiaFactor: 1.0,
        recommendedRpmMin: 10000,
        recommendedRpmMax: 45000,
        thrustCoefficient: 0.11,
        powerCoefficient: 0.045,
        rotationDirections: ['cw', 'ccw'],
      },
    },
  }),
  rev('prop-5x4.5x3', 'prop-5x4.5x3@1', {
    componentType: 'propeller',
    display: display('5x4.5x3', 'FluxCraft'),
    massKg: gramsToKg(4.5),
    dimensions: { widthMeters: m(0.127), lengthMeters: m(0.127), heightMeters: m(0.012) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['5mm'],
    compatibilityTags: ['5inch', 'freestyle'],
    dataQuality: curated,
    engineering: {
      type: 'propeller',
      propeller: {
        diameterMeters: m(0.127),
        pitchMeters: m(0.114),
        bladeCount: 3,
        rotationalInertiaFactor: 1.05,
        recommendedRpmMin: 9000,
        recommendedRpmMax: 42000,
        thrustCoefficient: 0.105,
        powerCoefficient: 0.048,
        rotationDirections: ['cw', 'ccw'],
      },
    },
  }),
  rev('prop-65mm-2blade', 'prop-65mm-2blade@1', {
    componentType: 'propeller',
    display: display('65mm 2-blade', 'MicroNest Labs'),
    massKg: gramsToKg(0.6),
    dimensions: { widthMeters: m(0.065), lengthMeters: m(0.065), heightMeters: m(0.006) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['1.5mm'],
    compatibilityTags: ['whoop'],
    dataQuality: curated,
    engineering: {
      type: 'propeller',
      propeller: {
        diameterMeters: m(0.065),
        pitchMeters: m(0.025),
        bladeCount: 2,
        rotationalInertiaFactor: 0.25,
        recommendedRpmMin: 15000,
        recommendedRpmMax: 55000,
        thrustCoefficient: 0.07,
        powerCoefficient: 0.03,
        rotationDirections: ['either'],
      },
    },
  }),
  rev('prop-6x4x3', 'prop-6x4x3@1', {
    componentType: 'propeller',
    display: display('6x4x3', 'Vector Forge'),
    massKg: gramsToKg(5.5),
    dimensions: { widthMeters: m(0.152), lengthMeters: m(0.152), heightMeters: m(0.014) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['5mm'],
    compatibilityTags: ['hybrid'],
    dataQuality: curated,
    engineering: {
      type: 'propeller',
      propeller: {
        diameterMeters: m(0.152),
        pitchMeters: m(0.102),
        bladeCount: 3,
        rotationalInertiaFactor: 1.3,
        recommendedRpmMin: 8000,
        recommendedRpmMax: 38000,
        thrustCoefficient: 0.12,
        powerCoefficient: 0.05,
        rotationDirections: ['cw', 'ccw'],
      },
    },
  }),
  rev('prop-7x4x3', 'prop-7x4x3@1', {
    componentType: 'propeller',
    display: display('7x4x3', 'Horizon Aero'),
    massKg: gramsToKg(7.5),
    dimensions: { widthMeters: m(0.178), lengthMeters: m(0.178), heightMeters: m(0.015) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['5mm'],
    compatibilityTags: ['7inch'],
    dataQuality: curated,
    engineering: {
      type: 'propeller',
      propeller: {
        diameterMeters: m(0.178),
        pitchMeters: m(0.102),
        bladeCount: 3,
        rotationalInertiaFactor: 1.6,
        recommendedRpmMin: 6000,
        recommendedRpmMax: 28000,
        thrustCoefficient: 0.125,
        powerCoefficient: 0.055,
        rotationDirections: ['cw', 'ccw'],
      },
    },
  }),

  // Batteries
  rev('batt-4s-2800', 'batt-4s-2800@1', {
    componentType: 'battery',
    display: display('4S 2800mAh', 'Skyward Dynamics'),
    massKg: gramsToKg(120),
    dimensions: { widthMeters: m(0.035), lengthMeters: m(0.1), heightMeters: m(0.03) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['strap'],
    compatibilityTags: ['4s'],
    dataQuality: curated,
    engineering: {
      type: 'battery',
      battery: {
        cellCount: 4,
        nominalVoltage: V(14.8),
        maxVoltage: V(16.8),
        capacityAh: mAhToAh(2800),
        dischargeCRating: 60,
        internalResistanceOhm: ohm(0.012),
        connectorType: 'xt60',
        voltageSagFactor: 0.08,
      },
    },
  }),
  rev('batt-6s-1500', 'batt-6s-1500@1', {
    componentType: 'battery',
    display: display('6S 1500mAh', 'Apex Racing Systems'),
    massKg: gramsToKg(195),
    dimensions: { widthMeters: m(0.04), lengthMeters: m(0.11), heightMeters: m(0.035) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['strap'],
    compatibilityTags: ['6s'],
    dataQuality: curated,
    engineering: {
      type: 'battery',
      battery: {
        cellCount: 6,
        nominalVoltage: V(22.2),
        maxVoltage: V(25.2),
        capacityAh: mAhToAh(1500),
        dischargeCRating: 100,
        internalResistanceOhm: ohm(0.018),
        connectorType: 'xt60',
        voltageSagFactor: 0.1,
      },
    },
  }),
  rev('batt-6s-2200', 'batt-6s-2200@1', {
    componentType: 'battery',
    display: display('6S 2200mAh', 'Vector Forge'),
    massKg: gramsToKg(280),
    dimensions: { widthMeters: m(0.045), lengthMeters: m(0.13), heightMeters: m(0.04) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['strap'],
    compatibilityTags: ['6s'],
    dataQuality: curated,
    engineering: {
      type: 'battery',
      battery: {
        cellCount: 6,
        nominalVoltage: V(22.2),
        maxVoltage: V(25.2),
        capacityAh: mAhToAh(2200),
        dischargeCRating: 80,
        internalResistanceOhm: ohm(0.02),
        connectorType: 'xt60',
        voltageSagFactor: 0.09,
      },
    },
  }),
  rev('batt-1s-450', 'batt-1s-450@1', {
    componentType: 'battery',
    display: display('1S 450mAh', 'MicroNest Labs'),
    massKg: gramsToKg(12),
    dimensions: { widthMeters: m(0.018), lengthMeters: m(0.04), heightMeters: m(0.01) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['ph2'],
    compatibilityTags: ['1s'],
    dataQuality: curated,
    engineering: {
      type: 'battery',
      battery: {
        cellCount: 1,
        nominalVoltage: V(3.7),
        maxVoltage: V(4.2),
        capacityAh: mAhToAh(450),
        dischargeCRating: 80,
        internalResistanceOhm: ohm(0.025),
        connectorType: 'ph2.0',
        voltageSagFactor: 0.12,
      },
    },
  }),
  rev('batt-6s-1800', 'batt-6s-1800@1', {
    componentType: 'battery',
    display: display('6S 1800mAh', 'FluxCraft'),
    massKg: gramsToKg(230),
    dimensions: { widthMeters: m(0.042), lengthMeters: m(0.12), heightMeters: m(0.038) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['strap'],
    compatibilityTags: ['6s'],
    dataQuality: curated,
    engineering: {
      type: 'battery',
      battery: {
        cellCount: 6,
        nominalVoltage: V(22.2),
        maxVoltage: V(25.2),
        capacityAh: mAhToAh(1800),
        dischargeCRating: 90,
        internalResistanceOhm: ohm(0.019),
        connectorType: 'xt60',
        voltageSagFactor: 0.095,
      },
    },
  }),
  rev('batt-6s-3000', 'batt-6s-3000@1', {
    componentType: 'battery',
    display: display('6S 3000mAh', 'Horizon Aero'),
    massKg: gramsToKg(380),
    dimensions: { widthMeters: m(0.05), lengthMeters: m(0.15), heightMeters: m(0.04) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['strap'],
    compatibilityTags: ['6s', 'long-range'],
    dataQuality: curated,
    engineering: {
      type: 'battery',
      battery: {
        cellCount: 6,
        nominalVoltage: V(22.2),
        maxVoltage: V(25.2),
        capacityAh: mAhToAh(3000),
        dischargeCRating: 50,
        internalResistanceOhm: ohm(0.022),
        connectorType: 'xt60',
        voltageSagFactor: 0.07,
      },
    },
  }),

  // ESCs
  rev('esc-4in1-45a', 'esc-4in1-45a@1', {
    componentType: 'esc',
    display: display('4-in-1 45A', 'Apex Racing Systems'),
    massKg: gramsToKg(12),
    dimensions: { widthMeters: m(0.04), lengthMeters: m(0.04), heightMeters: m(0.008) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['30.5x30.5', '20x20'],
    compatibilityTags: ['4in1'],
    dataQuality: curated,
    engineering: {
      type: 'esc',
      esc: {
        voltageMin: V(10),
        voltageMax: V(26),
        continuousCurrentA: A(45),
        burstCurrentA: A(55),
        protocols: ['dshot600', 'dshot300'],
        efficiency: 0.95,
        topology: '4in1',
      },
    },
  }),
  rev('esc-4in1-20a', 'esc-4in1-20a@1', {
    componentType: 'esc',
    display: display('4-in-1 20A', 'Skyward Dynamics'),
    massKg: gramsToKg(8),
    dimensions: { widthMeters: m(0.03), lengthMeters: m(0.03), heightMeters: m(0.006) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['20x20'],
    compatibilityTags: ['4in1'],
    dataQuality: curated,
    engineering: {
      type: 'esc',
      esc: {
        voltageMin: V(7),
        voltageMax: V(18),
        continuousCurrentA: A(20),
        burstCurrentA: A(25),
        protocols: ['dshot300'],
        efficiency: 0.93,
        topology: '4in1',
      },
    },
  }),
  rev('esc-4in1-12a', 'esc-4in1-12a@1', {
    componentType: 'esc',
    display: display('4-in-1 12A', 'MicroNest Labs'),
    massKg: gramsToKg(3),
    dimensions: { widthMeters: m(0.02), lengthMeters: m(0.02), heightMeters: m(0.004) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['16x16'],
    compatibilityTags: ['4in1', 'whoop'],
    dataQuality: curated,
    engineering: {
      type: 'esc',
      esc: {
        voltageMin: V(3),
        voltageMax: V(9),
        continuousCurrentA: A(12),
        burstCurrentA: A(15),
        protocols: ['dshot150'],
        efficiency: 0.9,
        topology: '4in1',
      },
    },
  }),

  // Electronics (mass + power)
  rev('fc-f7-standard', 'fc-f7-standard@1', {
    componentType: 'flight-controller',
    display: display('F7 FC', 'Official'),
    massKg: gramsToKg(6),
    dimensions: { widthMeters: m(0.036), lengthMeters: m(0.036), heightMeters: m(0.008) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['30.5x30.5', '20x20'],
    compatibilityTags: ['fc'],
    dataQuality: curated,
    engineering: {
      type: 'flight-controller',
      electronics: { powerDrawWatts: W(1.5), dragContribution: 0.02 },
    },
  }),
  rev('cam-fpv-standard', 'cam-fpv-standard@1', {
    componentType: 'camera',
    display: display('FPV Camera', 'Official'),
    massKg: gramsToKg(8),
    dimensions: { widthMeters: m(0.02), lengthMeters: m(0.02), heightMeters: m(0.02) },
    localCenterOfMass: vec3(0.02, 0, 0.01),
    mountingPatterns: ['camera'],
    compatibilityTags: ['camera'],
    dataQuality: curated,
    engineering: {
      type: 'camera',
      electronics: { powerDrawWatts: W(1.2), dragContribution: 0.05 },
    },
  }),
  rev('vtx-25-800', 'vtx-25-800@1', {
    componentType: 'video-transmitter',
    display: display('VTX 25-800mW', 'Official'),
    massKg: gramsToKg(7),
    dimensions: { widthMeters: m(0.03), lengthMeters: m(0.025), heightMeters: m(0.008) },
    localCenterOfMass: vec3(-0.02, 0, 0),
    mountingPatterns: ['vtx'],
    compatibilityTags: ['vtx'],
    dataQuality: curated,
    engineering: {
      type: 'video-transmitter',
      electronics: { powerDrawWatts: W(2.5), dragContribution: 0.03 },
    },
  }),
  rev('rx-elrs', 'rx-elrs@1', {
    componentType: 'receiver',
    display: display('ELRS Receiver', 'Official'),
    massKg: gramsToKg(1.5),
    dimensions: { widthMeters: m(0.015), lengthMeters: m(0.012), heightMeters: m(0.004) },
    localCenterOfMass: vec3(0, 0, 0),
    mountingPatterns: ['rx'],
    compatibilityTags: ['elrs'],
    dataQuality: curated,
    engineering: {
      type: 'receiver',
      electronics: { powerDrawWatts: W(0.4), dragContribution: 0.01 },
    },
  }),
];

export const OFFICIAL_CATALOG_RELEASE: CatalogRelease = {
  releaseId: asCatalogReleaseId('official-catalog-1.1.0'),
  version: '1.1.0',
  componentRevisionIds: OFFICIAL_COMPONENT_REVISIONS.map((r) => r.revisionId),
  publishedAtIso: null,
  label: 'Official Catalog v1.1.0',
};

export function buildOfficialCatalogSnapshot(): ComponentCatalogSnapshot {
  const revisions = new Map<ComponentRevisionId, ComponentRevision>();
  for (const r of OFFICIAL_COMPONENT_REVISIONS) {
    revisions.set(r.revisionId, r);
  }
  return { release: OFFICIAL_CATALOG_RELEASE, revisions };
}

export function getRevision(
  snapshot: ComponentCatalogSnapshot,
  revisionId: ComponentRevisionId | string,
): ComponentRevision | undefined {
  return snapshot.revisions.get(revisionId as ComponentRevisionId);
}
